# Generated by Django 5.1.3 on 2024-11-05 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_dealer_alter_game_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealt_games', to='polls.player'),
        ),
        migrations.DeleteModel(
            name='Dealer',
        ),
    ]
