# Generated by Django 5.1.3 on 2024-11-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_game_dealer_delete_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='out',
            field=models.BooleanField(default=False),
        ),
    ]
