# Generated by Django 5.1.3 on 2024-11-06 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_game_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('out', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='out',
        ),
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
        migrations.AddField(
            model_name='player',
            name='playerbase_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.playerbase'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('playerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.playerbase')),
                ('max_score', models.IntegerField(default=17)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer', to='polls.game')),
            ],
            bases=('polls.playerbase',),
        ),
    ]
